reflectoring:
  trace: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG  # For request/response details

spring:
  datasource:
    url: jdbc:h2:mem:testdb;init=CREATE SCHEMA IF NOT EXISTS edge
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
